config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  #/login, /logout
  devise_for :users, :path => "/", :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {:sessions => "sessions"}
  #/login, /logout

  get '404', :to => 'application#page_not_found', as: :no_route

  get 'project/check' => 'project/check#check', as: :check_project

  resource :project, :only => [] do
    get 'new' => 'project', as: :new
    post '/' => 'project#create', as: :create
    get ':id' => 'project#edit', as: :edit
    post ':id' => 'project#update', as: :update
    delete ':id' => 'project#destroy', as: :destroy
    post ':id/upload' => 'project/upload#upload', as: :upload
    get ':id/show' => 'project/show#index', as: :show
  end

  root :to => 'root#index'
end

app/views/layouts/_footer.html.erb
<div class="text-center">
  <p>
    <small class="text-muted">Mercury Development &copy; 2015</small>
  </p>
</div>

app/views/layouts/_navbar.html.erb
<!-- header -->
<header id="header" class="app-header navbar" role="menu">
  <!-- navbar header -->
  <div class="navbar-header bg-primary">
    <button class="pull-right visible-xs dk" ui-toggle-class="show" target=".navbar-collapse">
      <i class="glyphicon glyphicon-cog"></i>
    </button>
    <button class="pull-right visible-xs" ui-toggle-class="off-screen" target=".app-aside" ui-scroll="app">
      <i class="glyphicon glyphicon-align-justify"></i>
    </button>
    <!-- brand -->
    <a href="#/" class="navbar-brand text-lt">
      <span class="hidden-folded m-l-xs">Build check</span>
    </a>
    <!-- / brand -->
  </div>
  <!-- / navbar header -->

  <!-- navbar collapse -->
  <div class="collapse pos-rlt navbar-collapse box-shadow bg-white-only">

    <!-- nabar right -->
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <%= link_to raw('<span>Logout</span>'), destroy_user_session_path, method: :delete %>
      </li>
    </ul>
    <!-- / navbar right -->
  </div>
  <!-- / navbar collapse -->
</header>
<!-- / header -->


<!-- aside -->
<aside id="aside" class="app-aside hidden-xs bg-dark">
  <div class="aside-wrap">
    <div class="navi-wrap">

      <!-- nav -->
      <nav ui-nav class="navi clearfix">
        <ul class="nav">
          <li style="margin-top: 12px">
            <%= link_to raw('<span>New project</span>'), new_project_path %>
          </li>

          <li class="line dk" style="margin: 13px 0px"></li>

          <% current_user.projects.each do |project| %>
              <li>
                <%= link_to raw('<b class="badge bg-info pull-right">iOS</b><span>Project - %s</span>' % project.name), show_project_path(project) %>
              </li>
          <% end %>
        </ul>
      </nav>
      <!-- nav -->

    </div>
  </div>
</aside>
<!-- / aside -->

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= Rails.configuration.site_name %></title>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="/css/animate.css" type="text/css"/>
  <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css"/>
  <link rel="stylesheet" href="/css/bootstrap/bootstrap.css" type="text/css"/>
  <link rel="stylesheet" href="/css/font.css" type="text/css"/>
  <link rel="stylesheet" href="/css/app.css" type="text/css"/>

  <%= javascript_include_tag 'application' %>
  <script src="/js/bootstrap/bootstrap.min.js"></script>

  <link rel="stylesheet" href="/css/simple-line-icons.css" type="text/css"/>
</head>
<body>
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
     chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a
    different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a>
    to experience this site.</p><![endif]-->

<div class="app app-header-fixed ">
  <% if root_page? %>
      <link rel="stylesheet" href="/css/root.css" type="text/css"/>
      <%= yield %>
  <% else %>
      <% if current_user %>

          <!-- content -->
          <%= render partial: 'layouts/navbar' %>

          <div id="content" class="app-content" role="main">
            <div class="app-content-body ">

              <%= yield %>

            </div>
          </div>

      <% else %>
          <%= yield %>
      <% end %>
  <% end %>
</div>

<script src="/js/ui-load.js"></script>
<script src="/js/ui-jp.config.js"></script>
<script src="/js/ui-jp.js"></script>
<script src="/js/ui-nav.js"></script>
<script src="/js/ui-toggle.js"></script>
<script src="/js/ui-client.js"></script>

</body>
</html>